"""Add Review Model

Revision ID: d4689d1393f0
Revises: a340aff657e8
Create Date: 2024-03-17 20:02:56.294329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4689d1393f0'
down_revision = 'a340aff657e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
